### ISSUE TITLE
Docker: Unable to run confluent login from console

### ISSUE THREAD

**Issue by jonshipman** [confluentinc/cli#2390]
Using the docker image, I am unable to get `confluent login` to work. Building a custom image that echos what gets passed into x-www-browser and using the url on another machine results in a timeout.

![confluent](https://github.com/confluentinc/cli/assets/12699954/73ca172e-301b-4771-9c11-312953cb76ed)

**Comment by brianstrauch** [comment]
Hi, this URL isn't designed to be used on another machine. On login, the CLI will start a local server (in this example, port 26635) and wait for a callback. If you open this URL on another machine, there won't be a local server running so the callback will wait and eventually time out.

It looks like you're trying to log in with Google from a Docker machine, which requires a browser... The only solutions I can offer here are 1. Create a new username/password account instead of Google log-in, or if that's not possible 2. Use a headless browser from inside the Docker image. Here's an example of how that process works (using Okta instead of Google): https://github.com/confluentinc/cli-plugins/tree/main/confluent-login-headless_sso
